version: '3.1'

services:

  web:
    image: jonev/home-hosting:events-api
    environment:
      MYSQL_HOST: db
      MYSQL_PASSWORD: aaa
      CLIENT_ID: aaa
    ports:
    - 9000:8080
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: aaa
      MYSQL_DATABASE: event_db

  adminer:
    image: adminer
    ports:
      - 8081:8080